import FreeSimpleGUI as sg


def create_jukebox_selection_screen_layout(MusicMasterSongList, selection_window_number, dir_path):
    """
    Creates the jukebox selection screen layout.

    Args:
        MusicMasterSongList: The master list of songs with title and artist information
        selection_window_number: The current window number to display songs from
        dir_path: The directory path for image files

    Returns:
        A PySimpleGUI layout list for the selection screen
    """
    jukebox_selection_screen_layout = [
        [sg.Button(button_text="A1", key='--A1--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0), font='Helvetica 16 bold'),
        sg.Button(button_text=MusicMasterSongList[selection_window_number]['title'][:22], size=(22, 1),
                   key='--button0_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
        sg.Button(button_text="B1", key='--B1--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
        sg.Button(button_text=MusicMasterSongList[selection_window_number + 14]['title'][:22], size=(22, 1),
                   key='--button7_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
        sg.Button(button_text="C1", key='--C1--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
        sg.Button(button_text=MusicMasterSongList[selection_window_number + 28]['title'][:22], size=(22, 1),
                   key='--button14_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white',
                   font='Helvetica 12 bold')],
        [sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number]['artist'][:22], size=(22, 1),
                   key='--button0_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)),button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 14]['artist'][:22], size=(22, 1),
                   key='--button7_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 28]['artist'][:22], size=(22, 1),
                   key='--button14_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold')],
        [sg.Button(button_text="A2", key='--A2--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 2]['title'][:22], size=(22, 1),
                   key='--button1_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="B2", key='--B2--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 16]['title'][:22], size=(22, 1),
                   key='--button8_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="C2", key='--C2--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 30]['title'][:22], size=(22, 1),
                   key='--button15_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold')],
        [sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 2]['artist'][:22], size=(22, 1),
                   key='--button1_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 16]['artist'][:22], size=(22, 1),
                   key='--button8_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 30]['artist'][:22], size=(22, 1),
                   key='--button15_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold')],
        [sg.Button(button_text="A3", key='--A3--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 4]['title'][:22], size=(22, 1),
                   key='--button2_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="B3", key='--B3--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 18]['title'][:22], size=(22, 1),
                   key='--button9_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="C3", key='--C3--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 32]['title'][:22], size=(22, 1),
                   key='--button16_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold')],
        [sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 4]['artist'][:22], size=(22, 1),
                   key='--button2_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 18]['artist'][:22], size=(22, 1),
                   key='--button9_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 32]['artist'][:22], size=(22, 1),
                   key='--button16_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold')],
        [sg.Button(button_text="A4", key='--A4--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 6]['title'][:22], size=(22, 1),
                   key='--button3_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="B4", key='--B4--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 20]['title'][:22], size=(22, 1),
                   key='--button10_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="C4", key='--C4--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 34]['title'][:22], size=(22, 1),
                   key='--button17_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold')],
        [sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 6]['artist'][:22], size=(22, 1),
                   key='--button3_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 20]['artist'][:22], size=(22, 1),
                   key='--button10_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 34]['artist'][:22], size=(22, 1),
                   key='--button17_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold')],
        [sg.Button(button_text="A5", key='--A5--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 8]['title'][:22], size=(22, 1),
                   key='--button4_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="B5", key='--B5--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 22]['title'][:22], size=(22, 1),
                   key='--button11_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="C5", key='--C5--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 36]['title'][:22], size=(22, 1),
                   key='--button18_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold')],
        [sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 8]['artist'][:22], size=(22, 1),
                   key='--button4_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 22]['artist'][:22], size=(22, 1),
                   key='--button11_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 36]['artist'][:22], size=(22, 1),
                   key='--button18_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold')],
        [sg.Button(button_text="A6", key='--A6--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 10]['title'][:22], size=(22, 1),
                   key='--button5_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="B6", key='--B6--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number +24]['title'][:22], size=(22, 1),
                   key='--button12_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="C6", key='--C6--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 38]['title'][:22], size=(22, 1),
                   key='--button19_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold')],
        [sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 10]['artist'][:22], size=(22, 1),
                   key='--button5_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 24]['artist'][:22], size=(22, 1),
                   key='--button12_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 38]['artist'][:22], size=(22, 1),
                   key='--button19_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold')],
        [sg.Button(button_text="A7", key='--A7--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 12]['title'][:22], size=(22, 1),
                   key='--button6_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="B7", key='--B7--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 26]['title'][:22], size=(22, 1),
                   key='--button13_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text="C7", key='--C7--', size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_bg.png', border_width=0, pad=(0, 0),
                   font='Helvetica 16 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 40]['title'][:22], size=(22, 1),
                   key='--button20_top--', image_filename=dir_path + '/images/new_selection_top_bg.png', border_width=0,
                   pad=(0, 0), button_color='black on white', font='Helvetica 12 bold')],
        [sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 12]['artist'][:22], size=(22, 1),
                   key='--button6_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, pad=(0, (0, 0)), button_color='black on white', font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 26]['artist'][:22], size=(22, 1),
                   key='--button13_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold'),
         sg.Button(button_text=" ", size=(30, 26), image_size=(30, 26),
                   image_filename=dir_path + '/images/button_id_black_bg.png',
                   border_width=0, pad=(0, 0), font='Helvetica 11 bold'),
         sg.Button(button_text=MusicMasterSongList[selection_window_number + 40]['artist'][:22], size=(22, 1),
                   key='--button20_bottom--', image_filename=dir_path + '/images/new_selection_top_bg.png',
                   border_width=0, button_color='black on white', pad=(0, (0, 0)), font='Helvetica 12 bold')],
        # 22 char Limit
        ]

    return jukebox_selection_screen_layout
